### ISSUE TITLE
Incremental Backup module

### ISSUE THREAD

**Issue by mattymatty97** [Polarbub/MC-Server-Bot#11]
Add git based backups for the running server

Additional:
-  in game commands

**Comment by Polarbub** [comment]
what method of compression are you going to use?

**Comment by Polarbub** [comment]
Also how are you going to do in game commands? Are you going to use a fabric mod and some networking to communicate? Or a magic proxy?

**Comment by mattymatty97** [comment]
incremental backups do no t need compressions

> 
> 
> What method of compression are you going to use?

**Comment by mattymatty97** [comment]
> 
> 
> Also how are you going to do in game commands? Are you going to use a fabric mod and some networking to communicate? Or a magic proxy?

neither of them some magic regex to get player typed messages as bot commands

**Comment by Polarbub** [comment]
well then I'll have 160GB of backups assuming you have 4 backups

**Comment by mattymatty97** [comment]
incremental backups are meant to reduce the memory used to store them:
instead of saving the entire space it only saves the differences between the current status and the previews saved one

**Comment by Polarbub** [comment]
ohhh

**Comment by Polarbub** [comment]
So lets say I run a backup. It goes through and finds all the differences from the last backup and those get backed up? Then there is 3 backup folders, 1 hour, 18 hours and 3 days each of these runs on their schedule.

**Comment by mattymatty97** [comment]
you'll not have a backup folder, as i'll use git commits as backups you'll have a .git folder where git will do it's magic and use git commands  ( or the bot commands that will wrap up git  ones) to do and restore backups

**Comment by mattymatty97** [comment]
also as it's using git you'll be able ( eventually and possibly not) to upload ( git push) the entiry server to github or an external server used as storage

**Comment by Polarbub** [comment]
kk. Smart. As for off site storage my upload speed is ~4Mbps so you could allocate ~1Mbps to backups and ~3Mbps to the server. 

Also can you use one of those infinity big google drive things as off site backups?

**Comment by mattymatty97** [comment]
bruh and nope i need either a private github repo ( or pubblic choose u ) or a secondary server where to have a git instance.
also git will "steal" upload speed only rarely and for almost instant transmissions so it wont affect the server nor the players

**Comment by Polarbub** [comment]
the server just crashed during a backup. I raised the priority.

**Comment by polarbub** [comment]
you need to stop the server while backing up to stop file access conflicts please fix
