### ISSUE TITLE
emoji

### ISSUE THREAD

**Issue by polarbub** [polarbub/MC-Server-Bot#20]
When an emoji is sent in the chat bridge such as 😄 put `:smile:` in minecraft chat.

**Comment by Polarbub** [comment]
and make `:smile` in mc chat 😄 in discord.

**Comment by mattymatty97** [comment]
this is harder than expected as Discord convertis base emoticons in UTF-8 characheters and there is no known way to do the inverse

**Comment by Polarbub** [comment]
Massive truth table? But that would take a while but be the cleanest solution. There might be a open source bot that does this I'm playing with it rn.

Or maybe something like Emoji-er where if you want the emoji to come up you have to do `.protosky.copypaste.` for a foreign server's emoji and that would put `:copypaste:` in chat. Or you could just do `.copypaste.` or for a local server's emoji

**Comment by Polarbub** [comment]
this thing: https://github.com/vcokltfre/ArcosBot and the !chars command

**Comment by Polarbub** [comment]
I can't figure out how to make this work `from config.config import token, name, log_level, log_type`

**Comment by mattymatty97** [comment]
> 
> 
> I can't figure out how to make this work `from config.config import token, name, log_level, log_type`

cause that's a  python command and we're working in javascript xD

**Comment by mattymatty97** [comment]
> 
> 
> Massive truth table? But that would take a while but be the cleanest solution. There might be a open source bot that does this I'm playing with it rn.
> 
> Or maybe something like Emoji-er where if you want the emoji to come up you have to do `.protosky.copypaste.` for a foreign server's emoji and that would put `:copypaste:` in chat. Or you could just do `.copypaste.` or for a local server's emoji

problem is not from mc to discord but the vice-versa

**Comment by Polarbub** [comment]
yes .copypaste. in discord goes into :copypaste: in mc. Then the the normal emojier thing happens as if .copypaste. was its command

**Comment by Polarbub** [comment]
how do I set those? cause that's a python command and we're working in javascript xD

**Comment by mattymatty97** [comment]
python and javascript are two different languages you cant use commands from on to the other. you need to find the javascript version of that program/module

**Comment by Polarbub** [comment]
python and javascript are two different languages you cant use commands from on to the other. you need to find the javascript version of that program/module.
yes I know that it would have to be converted to js to make it work
but how do I set those variables as I want to test the arcos bot in its current state.

**Comment by Polarbub** [comment]
big brain time: just say the Unicode character name and make a regex for custom emoji so they don't have <> and an id

**Comment by Polarbub** [comment]
also going from mc to discord custom emojis don't work

**Comment by polarbub** [comment]
Fixed in the java version
