### ISSUE TITLE
@polarbub shows up weirdly in mc chat

### ISSUE THREAD

**Issue by Polarbub** [Polarbub/MC-Server-Bot#26]
`@polarbub` shows up with an extra unknown character 
...^there.

**Comment by mattymatty97** [comment]
all discord specific things are in discord format
so emojis ( except default ones ) are `<:name:03473947124812689>` where the numbers are the emoji ID,
roles mentions are `<@&ROLEID>`.
user mentions are `<@USERID>`.
and channels are `<#CHANNELID>`
