### ISSUE TITLE
.bot command for carpet bots

### ISSUE THREAD

**Issue by Polarbub** [Polarbub/MC-Server-Bot#3]
`.bot` 
options:
`.bot spawn <bot name> <player to spawn at's name>` (spawns a carpet bot)
`.bot remove <bot name>` (removes a bot)
and 
`.bot list` (lists bots)

so `.bot spawn bee Google_Alt`
and `.bot remove bee`

and there is a bot cap of 5

I think carpet bots get removed at server restart so no need to write down the names of the bots in a .json file.

For the bot cap you could use a global variable that gets added to or subtracted from every time one of the commands is run. 

If you wanted to go above and beyond you could at `.stop` save the all bots settings to a .json file to remember them for the next time the server is `.start`ed

**Comment by Polarbub** [comment]
I also need to figure out how to do permissions to not let anyone do it in mc. If you could do a bot cap in mc then there is no need for this module

**Comment by polarbub** [comment]
no real need, just using admins is fine
