### ISSUE TITLE
.apply

### ISSUE THREAD

**Issue by Polarbub** [Polarbub/MC-Server-Bot#4]
Applications System:
End User Experience:
    IN: #bot-spam
        user: reacts to application message in #welcome
        IN: DMs
        bot: What is your ign?
User: `their ign`
    Bot: What could you bring to the server?
    Bot: Remember the more you give the more we have to work with.
User: `their reason`
Bot: Thank you for your application it will be soon reviewed

IN: #applications
Bot: User has Applied
Bot: Their ign is: `IGN`
Bot: Why they would like to be on Protosky is:
On a new line
Bot: `their reason`

Check, X and :alarm_clock: are reacted by the bot to the final message

people can vote on letting the person in with the x and check

Once the 48 hour voting period is up someone with `finish vote` permission reacts with the alarm clock finishing the vote and making sure the person is okay to join if the vote is in favor OR 48 hours is up.

The application is then moved to #archived-apps 

If the person is accepted then they are given the @Server Member role and their ign is whitelisted with .exec whitelist add `their ign`.

**Comment by Polarbub** [comment]
also it would be nice to have configurable questions

**Comment by polarbub** [comment]
no
