### ISSUE TITLE
Death regex

### ISSUE THREAD

**Issue by polarbub** [Polarbub/MC-Server-Bot#40]
When someone dies put the death message in the chat bridge.

**Comment by mattymatty97** [comment]
that's harder than you think

**Comment by mattymatty97** [comment]
you need a regex for every death message

**Comment by polarbub** [comment]
I realized that after making it

**Comment by polarbub** [comment]
but look at this
Arrows

    [player] was shot by arrow
        This message is caused by arrows shot from a dispenser or /summon
    [player] was shot by [player/mob]
        Caused by mobs with projectile attacks or kills using a bow.
    [player] was shot by [player/mob] using [bow name]
        Caused by mobs or players with a renamed bow

Cactus

    [player] was pricked to death
    [player] hugged a cactus
    [player] walked into a cactus while trying to escape [player/mob]
    [player] was stabbed to death
        Console Edition only

Drowning

    [player] drowned
    [player] drowned whilst trying to escape [player/mob]

Elytra

    [player] experienced kinetic energy
    [player] removed an elytra while flying

Explosions

    [player] blew up
    [player] was blown up by [player/mob]
        This message shows up only when TNT is activated by a creeper or by a player using flint and steel or an arrow shot from a bow enchanted with Flame

Falling

    [player] hit the ground too hard
        Only caused if the player is killed by a short fall, ender pearl damage, or riding an entity that died due to fall damage.
    [player] fell from a high place
        Caused by a fall greater than 5 blocks.
    [player] fell off a ladder
    [player] fell off some vines
    [player] fell out of the water
    [player] fell into a patch of fire
    [player] fell into a patch of cacti
    [player] was doomed to fall by [mob/player]
    [player] was shot off some vines by [mob/player]
    [player] was shot off a ladder by [mob/player]
    [player] was blown from a high place by [mob/player]
        Only caused if knockback from a creeper explosion, a ghast fireball, or player-lit TNT causes the player to fall to their death.

Falling blocks

    [player] was squashed by a falling anvil
    [player] was squashed by a falling block
        This message appears if the player is killed by a custom falling block other than an anvil that is modified to inflict damage

Fire

    [player] went up in flames
        This message appears if the player died while in the source of the fire (unless the game rule firedamage has been set to false).
    [player] burned to death
        This message appears if the player died while on fire, but not in the source (unless the game rule firedamage has been set to false).
    [player] was burnt to a crisp whilst fighting [player/mob]
    [player] walked into a fire whilst fighting [player/mob]

Firework rockets

    [player] went off with a bang

Lava

    [player] tried to swim in lava
    [player] tried to swim in lava while trying to escape [player/mob]

Lightning

    [player] was struck by lightning

Magma Block

    [player] discovered floor was lava

Players and mobs

    [player] was slain by [player/mob]
    [player] was slain by [player/mob] using [weapon]
        Caused by kills using a renamed weapon.
    [player] got finished off by [player/mob]
    [player] got finished off by [player/mob] using [weapon]
        Caused by kills using a renamed weapon.
    [player] was fireballed by [mob]
        Only caused by blazes and ghasts

Potions of Harming

    [player] was killed by magic
        Happens when the potion is shot from a dispenser, by drinking it, or with /effect
    [player] was killed by [player/mob] using magic
        Caused by witches, guardians, and kills using a splash potion

Starving

    [player] starved to death
        Caused if the difficulty is Hard or Hardcore

Suffocation

    [player] suffocated in a wall
        Happens if the player took suffocation damage from their head being in a block.
    [player] was squished too much
        Happens if the player took suffocation damage from the maxEntityCramming gamerule.

Thorns enchantment

    [player] was killed while trying to hurt [player/mob]
        Can be caused by a mob if it is able to wear armor, and can also occur while fighting guardians

Void

    [player] fell out of the world
        Also shown if the player is killed by the /kill command
    [player] fell from a high place and fell out of the world

Wither effect

    [player] withered away

Other

    [victim] was pummeled by [killer]
        This message would appear when killed by a snowball, an egg, a wither skull or an ender pearl
        This message is unused in the case of snowballs, chicken eggs, and ender pearls, because they do not cause damage to players hit by them.
        This message is currently only shown when the wither kills a player with a wither skull's impact.
    [player] died
        Pocket Edition only, used in some cases

**Comment by mattymatty97** [comment]
you can add them yourself just add more lines in the chatregex section

**Comment by mattymatty97** [comment]
remember: the first capturing group of the regex should be the message to be printed in discord and the second should be the target player/entity only

all the others goups ( parenthesis ) should be non capturing groups or have a id higher than 2

use https://regexr.com to help u build the regular expressions

**Comment by polarbub** [comment]
Too much work, could be done at a later date.
